# Generated by Django 2.2 on 2020-07-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(blank=True, help_text='Example: 6390', max_length=20, null=True, verbose_name='Zipcode')),
            ],
        ),
    ]
